[2024-12-03T23:23:16.376+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T23:23:17.194+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_variables_financieras.merge_data_var5 manual__2024-12-03T23:22:08.859829+00:00 [queued]>
[2024-12-03T23:23:19.592+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_variables_financieras.merge_data_var5 manual__2024-12-03T23:22:08.859829+00:00 [queued]>
[2024-12-03T23:23:19.594+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-03T23:23:19.804+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): merge_data_var5> on 2024-12-03 23:22:08.859829+00:00
[2024-12-03T23:23:19.958+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=862) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T23:23:19.959+0000] {standard_task_runner.py:63} INFO - Started process 879 to run task
[2024-12-03T23:23:19.916+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_variables_financieras', 'merge_data_var5', 'manual__2024-12-03T23:22:08.859829+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmpfyzsbr_x']
[2024-12-03T23:23:20.022+0000] {standard_task_runner.py:91} INFO - Job 421: Subtask merge_data_var5
[2024-12-03T23:23:20.716+0000] {task_command.py:426} INFO - Running <TaskInstance: process_variables_financieras.merge_data_var5 manual__2024-12-03T23:22:08.859829+00:00 [running]> on host 5e909a8df6c4
[2024-12-03T23:23:22.195+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_variables_financieras' AIRFLOW_CTX_TASK_ID='merge_data_var5' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T23:22:08.859829+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T23:22:08.859829+00:00'
[2024-12-03T23:23:22.216+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T23:23:22.287+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-12-03T23:23:22.390+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-03T23:23:22.391+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T23:23:22.479+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_variables_financieras, task_id=merge_data_var5, run_id=manual__2024-12-03T23:22:08.859829+00:00, execution_date=20241203T232208, start_date=20241203T232317, end_date=20241203T232322
[2024-12-03T23:23:22.730+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-03T23:23:22.870+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T23:23:22.895+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
