[2024-12-03T00:00:11.686+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T00:00:11.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_variables_financieras.merge_data_var4 scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T00:00:12.044+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_variables_financieras.merge_data_var4 scheduled__2024-12-02T00:00:00+00:00 [queued]>
[2024-12-03T00:00:12.045+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-03T00:00:12.096+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): merge_data_var4> on 2024-12-02 00:00:00+00:00
[2024-12-03T00:00:12.116+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_variables_financieras', 'merge_data_var4', 'scheduled__2024-12-02T00:00:00+00:00', '--job-id', '407', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmp37gzwcul']
[2024-12-03T00:00:12.120+0000] {standard_task_runner.py:91} INFO - Job 407: Subtask merge_data_var4
[2024-12-03T00:00:12.123+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=102203) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T00:00:12.124+0000] {standard_task_runner.py:63} INFO - Started process 102209 to run task
[2024-12-03T00:00:12.216+0000] {task_command.py:426} INFO - Running <TaskInstance: process_variables_financieras.merge_data_var4 scheduled__2024-12-02T00:00:00+00:00 [running]> on host 5e909a8df6c4
[2024-12-03T00:00:12.560+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_variables_financieras' AIRFLOW_CTX_TASK_ID='merge_data_var4' AIRFLOW_CTX_EXECUTION_DATE='2024-12-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-02T00:00:00+00:00'
[2024-12-03T00:00:12.563+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T00:00:12.587+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-12-03T00:00:12.605+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-03T00:00:12.609+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T00:00:12.624+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_variables_financieras, task_id=merge_data_var4, run_id=scheduled__2024-12-02T00:00:00+00:00, execution_date=20241202T000000, start_date=20241203T000011, end_date=20241203T000012
[2024-12-03T00:00:12.679+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-03T00:00:12.698+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
