[2024-10-12T00:00:09.748+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-12T00:00:09.818+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_employees.merge_data scheduled__2024-10-11T00:00:00+00:00 [queued]>
[2024-10-12T00:00:09.841+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_employees.merge_data scheduled__2024-10-11T00:00:00+00:00 [queued]>
[2024-10-12T00:00:09.842+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-12T00:00:10.141+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): merge_data> on 2024-10-11 00:00:00+00:00
[2024-10-12T00:00:10.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_employees', 'merge_data', 'scheduled__2024-10-11T00:00:00+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmpurqrv293']
[2024-10-12T00:00:10.162+0000] {standard_task_runner.py:91} INFO - Job 298: Subtask merge_data
[2024-10-12T00:00:10.168+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2840) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-12T00:00:10.170+0000] {standard_task_runner.py:63} INFO - Started process 2842 to run task
[2024-10-12T00:00:10.249+0000] {task_command.py:426} INFO - Running <TaskInstance: process_employees.merge_data scheduled__2024-10-11T00:00:00+00:00 [running]> on host 5e909a8df6c4
[2024-10-12T00:00:10.456+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_employees' AIRFLOW_CTX_TASK_ID='merge_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-11T00:00:00+00:00'
[2024-10-12T00:00:10.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-12T00:00:10.474+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-10-12T00:00:10.499+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-12T00:00:10.500+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-12T00:00:10.530+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_employees, task_id=merge_data, run_id=scheduled__2024-10-11T00:00:00+00:00, execution_date=20241011T000000, start_date=20241012T000009, end_date=20241012T000010
[2024-10-12T00:00:10.591+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-12T00:00:10.621+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-12T00:00:10.632+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
