[2024-12-01T02:53:01.883+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-01T02:53:02.552+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_variables_financieras.merge_data_var4 manual__2024-12-01T02:51:55.613716+00:00 [queued]>
[2024-12-01T02:53:05.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_variables_financieras.merge_data_var4 manual__2024-12-01T02:51:55.613716+00:00 [queued]>
[2024-12-01T02:53:05.501+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-12-01T02:53:05.607+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): merge_data_var4> on 2024-12-01 02:51:55.613716+00:00
[2024-12-01T02:53:05.653+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_variables_financieras', 'merge_data_var4', 'manual__2024-12-01T02:51:55.613716+00:00', '--job-id', '390', '--raw', '--subdir', 'DAGS_FOLDER/etl_prueba.py', '--cfg-path', '/tmp/tmpw9ikor6b']
[2024-12-01T02:53:05.707+0000] {standard_task_runner.py:91} INFO - Job 390: Subtask merge_data_var4
[2024-12-01T02:53:05.701+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8218) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-01T02:53:05.731+0000] {standard_task_runner.py:63} INFO - Started process 8231 to run task
[2024-12-01T02:53:06.158+0000] {task_command.py:426} INFO - Running <TaskInstance: process_variables_financieras.merge_data_var4 manual__2024-12-01T02:51:55.613716+00:00 [running]> on host 5e909a8df6c4
[2024-12-01T02:53:07.360+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_variables_financieras' AIRFLOW_CTX_TASK_ID='merge_data_var4' AIRFLOW_CTX_EXECUTION_DATE='2024-12-01T02:51:55.613716+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-01T02:51:55.613716+00:00'
[2024-12-01T02:53:07.440+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-01T02:53:07.656+0000] {base.py:84} INFO - Using connection ID 'postgres' for task execution.
[2024-12-01T02:53:07.852+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-12-01T02:53:07.875+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-01T02:53:08.042+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_variables_financieras, task_id=merge_data_var4, run_id=manual__2024-12-01T02:51:55.613716+00:00, execution_date=20241201T025155, start_date=20241201T025302, end_date=20241201T025308
[2024-12-01T02:53:08.577+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-12-01T02:53:08.775+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-01T02:53:08.803+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
